# Site settings
name: Amin Vishvam
title: Amin Vishvam | 20, AI Enthusiast, Future Data scientist, Techno savvy.
description:  20, AI Enthusiast, Future Data scientist, Techno savvy.
url: http://aminvishvam.tk/
baseurl: ""
email: vishvamamin55@gmail.com
cover: http://dishantrathi.tk/img/og.png
logo: http://dishantrathi.tk/img/emojis/technologist.png
resume: http://aminvishvam.tk/
social:
  - title: email
    url: mailto:vishvamamin@gmail.com
  - title: twitter
    url: https://twitter.com/vishvamamin55
  - title: instagram
    url: https://instagram.com/vishvam.amin
  - title: github
    url: https://github.com/aminvishvam
  - title: linkedin
    url: https://www.linkedin.com/in/vishvam-amin-048671132/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
